language: node_js
node_js:
    - "12"
sudo: true

addons:
    chrome: stable

branches:
    only:
        - master

before_script:
    - npm install

script:
    - ng test --watch=false --browsers=ChromeHeadless --prod
