site_name: DesignSafe Hazmapper User Guide
site_description: Hazmapper User Guide

nav:
    - Introduction: introduction.md
    - Accessing Hazmapper: accessing.md
    - Interface Overview: interface.md
    - Map Types: maps.md
    - Supported Asset Types: assets.md
    - Collaboration: collaboration.md

last_updated: Last updated 06/27/2022

copyright: © Copyright 2022, Texas Advanced Computing Center, University of Texas.

markdown_extensions:
 - toc:
 - tables:

theme: 
  name: readthedocs
  custom_dir: custom_theme/

plugins:
    - search
