import { File } from '../types/file';

export const filesMock: File[] = [
  {
    name: 'Folder 3',
    path: 'user/Folder_2/Folder_3',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 31000,
    nativePermissions: 'ALL',
    mimeType: 'text/directory',
    type: 'dir',
    url: 'https://designsafe-ci.org/data/browser/user/Folder_2/Folder_3/',
  },
  {
    name: 'Test Map 3.hazmapper',
    path: 'user/Folder_2/Folder_3/Test Map 3.hazmapper',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 7000,
    nativePermissions: 'READ_WRITE',
    mimeType: 'application/octet-stream',
    type: 'file',
    url: 'https://designsafe-ci.org/data/browser/user/Folder_2/Folder_3/Test%20Map%203.hazmapper',
  },
  {
    name: 'Folder_1',
    path: 'user/Folder_1',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 31,
    nativePermissions: 'ALL',
    mimeType: 'text/directory',
    type: 'dir',
    url: 'https://designsafe-ci.org/data/browser/user/Folder_1/',
  },
  {
    name: 'Folder_2',
    path: 'user/Folder_2',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 4096,
    nativePermissions: 'ALL',
    mimeType: 'text/directory',
    type: 'dir',
    url: 'https://designsafe-ci.org/data/browser/user/Folder_2/',
  },
  {
    name: 'New Map.hazmapper',
    path: 'user/New Map.hazmapper',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 70,
    nativePermissions: 'READ_WRITE',
    mimeType: 'application/octet-stream',
    type: 'file',
    url: 'https://designsafe-ci.org/data/browser/user/New%20Map.hazmapper',
  },
  {
    name: 'Test Map.hazmapper',
    path: 'user/Test Map.hazmapper',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 70,
    nativePermissions: 'READ_WRITE',
    mimeType: 'application/octet-stream',
    type: 'file',
    url: 'https://designsafe-ci.org/data/browser/user/Test%20Map.hazmapper',
  },
  {
    name: 'Test Map 2.hazmapper',
    path: 'user/Folder_2/Test Map 2.hazmapper',
    lastModified: '2024-02-22T17:04:04.000-06:00',
    size: 70,
    nativePermissions: 'READ_WRITE',
    mimeType: 'application/octet-stream',
    type: 'file',
    url: 'https://designsafe-ci.org/data/browser/user/Folder_2/Test%20Map%202.hazmapper',
  },
];
