export const systems = {
  result: [
    {
      id: 'project-1234abcd-ab12-ab12-ab12-123456789abc',
      systemType: 'LINUX',
      owner: 'wma_prtl',
      host: 'cloud.corral.tacc.utexas.edu',
      effectiveUserId: 'tg458981',
      defaultAuthnMethod: 'PKI_KEYS',
      canExec: 'false',
      parentId: null,
    },
    {
      id: 'designsafe.storage.default',
      systemType: 'LINUX',
      owner: 'wma_prtl',
      host: 'cloud.data.tacc.utexas.edu',
      effectiveUserId: 'username',
      defaultAuthnMethod: 'PKI_KEYS',
      canExec: 'false',
      parentId: null,
    },
    {
      id: 'designsafe.storage.community',
      systemType: 'LINUX',
      owner: 'wma_prtl',
      host: 'cloud.data.tacc.utexas.edu',
      effectiveUserId: 'tg458981',
      defaultAuthnMethod: 'PKI_KEYS',
      canExec: 'false',
      parentId: null,
    },
  ],
  status: 'success',
  message: 'TAPIS_FOUND Systems found: 3 systems',
  version: '1.7.0',
  commit: '2eee8fa0',
  build: '2024-09-09T14:15:04Z',
  metadata: {
    recordCount: 3,
    recordLimit: 100,
    recordsSkipped: 0,
    orderBy: null,
    startAfter: null,
    totalCount: -1,
  },
};
