export const tileServerLayers = [
  {
    id: 134,
    name: 'Roads',
    type: 'tms',
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    tileOptions: {
      maxZoom: 24,
      minZoom: 0,
      maxNativeZoom: 19,
    },
    uiOptions: {
      zIndex: 0,
      opacity: 0.9,
      isActive: true,
      showInput: false,
      showDescription: true,
    },
  },
  {
    id: 133,
    name: 'Satellite',
    type: 'tms',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    attribution:
      'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
    tileOptions: {
      maxZoom: 24,
      minZoom: 0,
      maxNativeZoom: 19,
    },
    uiOptions: {
      zIndex: 1,
      opacity: 0.5,
      isActive: true,
      showInput: false,
      showDescription: false,
    },
  },
  {
    id: 517,
    name: 'PineRidge_20190330',
    type: 'arcgis',
    url: 'https://tiles.arcgis.com/tiles/JL4BwWcjcPuWhBm9/arcgis/rest/services/PineRidgeSchool_20190330/MapServer',
    attribution: '',
    tileOptions: {
      maxZoom: 24,
      minZoom: 0,
      maxNativeZoom: 19,
    },
    uiOptions: {
      zIndex: -2,
      opacity: 0.5,
      isActive: true,
      showInput: false,
      showDescription: false,
    },
  },
  {
    id: 521,
    name: 'PonderosaElementary_20190328',
    type: 'arcgis',
    url: 'https://tiles.arcgis.com/tiles/JL4BwWcjcPuWhBm9/arcgis/rest/services/PonderosaElementary_20190328/MapServer',
    attribution: '',
    tileOptions: {
      maxZoom: 24,
      minZoom: 0,
      maxNativeZoom: 19,
    },
    uiOptions: {
      zIndex: -1,
      opacity: 0.5,
      isActive: true,
      showInput: false,
      showDescription: false,
    },
  },
  {
    id: 515,
    name: 'AchieveCharterSchool_20190328',
    type: 'arcgis',
    url: 'https://tiles.arcgis.com/tiles/JL4BwWcjcPuWhBm9/arcgis/rest/services/AchieveCharterSchool_20190328/MapServer',
    attribution: '',
    tileOptions: {
      maxZoom: 24,
      minZoom: 0,
      maxNativeZoom: 19,
    },
    uiOptions: {
      zIndex: -4,
      opacity: 0.5,
      isActive: true,
      showInput: false,
      showDescription: false,
    },
  },
  {
    id: 516,
    name: 'Hospital_20190329',
    type: 'arcgis',
    url: 'https://tiles.arcgis.com/tiles/JL4BwWcjcPuWhBm9/arcgis/rest/services/Hospital_20190329/MapServer',
    attribution: '',
    tileOptions: {
      maxZoom: 24,
      minZoom: 0,
      maxNativeZoom: 19,
    },
    uiOptions: {
      zIndex: -3,
      opacity: 0.5,
      isActive: true,
      showInput: false,
      showDescription: false,
    },
  },
  {
    id: 648,
    name: 'Global Multi-Resolution Topography (GMRT) Synthesis',
    type: 'wms',
    url: 'https://www.gmrt.org/services/mapserver/wms_merc?request=GetCapabilities&service=WMS&version=1.3.0',
    attribution: '',
    tileOptions: {
      layers: 'GMRT',
    },
    uiOptions: {
      zIndex: 0,
      opacity: 0.5,
      isActive: true,
    },
  },
];
