name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  Angular-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm

      - name: npm ci
        working-directory: angular
        run: |
          touch src/environments/jwt.js
          npm ci

      - name: Unit Tests
        working-directory: angular
        run: npm run test:ci

  Angular-Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm

      - name: npm ci
        working-directory: angular
        run: npm ci

      - name: Linting
        working-directory: angular
        run: npm run lint

  React-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: npm ci
        working-directory: react
        run: npm ci

      - name: Unit Tests
        working-directory: react
        run: |
          cp src/secret_local.example.ts src/secret_local.ts
          npm run test

  React-Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: npm ci
        working-directory: react
        run: npm ci

      - name: Linting
        working-directory: react
        run: npm run lint

  React-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: npm ci
        working-directory: react
        run: npm ci

      - name: Build
        working-directory: react
        run: |
          cp src/secret_local.example.ts src/secret_local.ts
          npm run build
